import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'engineering-toolkit',
    {
      type: 'category',
      label: 'Cookbooks',
      items: [{type: 'autogenerated', dirName: 'cookbooks'}],
    },
    {
      type: 'category',
      label: 'Vision',
      items: [{type: 'autogenerated', dirName: 'vision'}],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'AI Skills',
      items: [{type: 'autogenerated', dirName: 'skills'}],
    },
    {
      type: 'category',
      label: 'Success Stories',
      items: [
        'success-stories/index',
        'success-stories/oalint-improved-code-quality',
        'success-stories/faster-ci-with-gh-actions',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: ['team/index', 'about/martin-pokorny', 'community/license', 'community/disclaimer'],
    },
  ],
};

export default sidebars;
